In [1]:
import torch
from torch.nn import functional as F

## indexing

In [2]:
x = torch.rand(5, 3)
x

tensor([[0.0724, 0.3986, 0.9197],
        [0.8268, 0.1867, 0.1764],
        [0.5295, 0.1778, 0.6780],
        [0.4695, 0.4074, 0.1313],
        [0.3981, 0.5832, 0.2968]])

In [3]:
x.shape

torch.Size([5, 3])

In [4]:
x.shape[1]

3

In [5]:
x[0]

tensor([0.0724, 0.3986, 0.9197])

In [6]:
p = torch.zeros(10)
p

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
y = torch.tensor([3, 8, 3, 3, 8, 5])
y

tensor([3, 8, 3, 3, 8, 5])

In [8]:
p.index_add_(0, y, torch.ones(y.shape[0]))
p

tensor([0., 0., 0., 3., 0., 1., 0., 0., 2., 0.])

In [41]:
x = torch.rand(4, 3, 2)
x

tensor([[[0.2779, 0.4963],
         [0.3669, 0.6873],
         [0.8190, 0.4531]],

        [[0.9211, 0.8597],
         [0.1782, 0.4656],
         [0.9413, 0.0126]],

        [[0.6139, 0.6560],
         [0.5021, 0.5460],
         [0.3308, 0.3145]],

        [[0.7076, 0.2332],
         [0.5789, 0.8032],
         [0.3484, 0.7074]]])

In [42]:
x[0:2]

tensor([[[0.2779, 0.4963],
         [0.3669, 0.6873],
         [0.8190, 0.4531]],

        [[0.9211, 0.8597],
         [0.1782, 0.4656],
         [0.9413, 0.0126]]])

## dimensions manipulation

In [9]:
x = torch.tensor([[0, 1, 1, 1], [2, 2, 0, 0]])
print(x.shape)
x

torch.Size([2, 4])


tensor([[0, 1, 1, 1],
        [2, 2, 0, 0]])

In [10]:
y = F.one_hot(x)
print(y.shape)
y

torch.Size([2, 4, 3])


tensor([[[1, 0, 0],
         [0, 1, 0],
         [0, 1, 0],
         [0, 1, 0]],

        [[0, 0, 1],
         [0, 0, 1],
         [1, 0, 0],
         [1, 0, 0]]])

In [11]:
order = list(range(0, y.ndim))
order.insert(1, order[-1])
del order[-1]
order

[0, 2, 1]

In [12]:
t = y.permute(order)
print(t.shape)
t

torch.Size([2, 3, 4])


tensor([[[1, 0, 0, 0],
         [0, 1, 1, 1],
         [0, 0, 0, 0]],

        [[0, 0, 1, 1],
         [0, 0, 0, 0],
         [1, 1, 0, 0]]])

In [13]:
s = torch.tensor([0.1, 0.2, 0.3, 0.4])
s

tensor([0.1000, 0.2000, 0.3000, 0.4000])

In [14]:
t.float() + s

tensor([[[1.1000, 0.2000, 0.3000, 0.4000],
         [0.1000, 1.2000, 1.3000, 1.4000],
         [0.1000, 0.2000, 0.3000, 0.4000]],

        [[0.1000, 0.2000, 1.3000, 1.4000],
         [0.1000, 0.2000, 0.3000, 0.4000],
         [1.1000, 1.2000, 0.3000, 0.4000]]])

In [15]:
t.float().lerp(s, 0.5)

tensor([[[0.5500, 0.1000, 0.1500, 0.2000],
         [0.0500, 0.6000, 0.6500, 0.7000],
         [0.0500, 0.1000, 0.1500, 0.2000]],

        [[0.0500, 0.1000, 0.6500, 0.7000],
         [0.0500, 0.1000, 0.1500, 0.2000],
         [0.5500, 0.6000, 0.1500, 0.2000]]])

## stack vs cat

In [16]:
x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
y = torch.ones(5, 3)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
c = torch.cat((x, y), dim = 0)
c

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
s = torch.stack((x, y), dim=0)
s

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [20]:
torch.mean(s, dim=0)

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])

## argsort

In [21]:
a = torch.rand((5, 3))
a

tensor([[0.1682, 0.5588, 0.2389],
        [0.2448, 0.4801, 0.7754],
        [0.8878, 0.0942, 0.8037],
        [0.4792, 0.4068, 0.3187],
        [0.7421, 0.8515, 0.9971]])

In [22]:
b = torch.rand((5, 3, 2))
b

tensor([[[0.6364, 0.8488],
         [0.4776, 0.9110],
         [0.0848, 0.9282]],

        [[0.2569, 0.6295],
         [0.4548, 0.0289],
         [0.9882, 0.3564]],

        [[0.4712, 0.3005],
         [0.7368, 0.3270],
         [0.8310, 0.8293]],

        [[0.7726, 0.2401],
         [0.1018, 0.9630],
         [0.8617, 0.4635]],

        [[0.3909, 0.1082],
         [0.9865, 0.1186],
         [0.9662, 0.9263]]])

In [23]:
x = torch.tensor([10, 5, 0, 20, 30])
x

tensor([10,  5,  0, 20, 30])

In [24]:
s = torch.argsort(x)
s

tensor([2, 1, 0, 3, 4])

In [25]:
torch.index_select(a, dim=0, index=s)

tensor([[0.8878, 0.0942, 0.8037],
        [0.2448, 0.4801, 0.7754],
        [0.1682, 0.5588, 0.2389],
        [0.4792, 0.4068, 0.3187],
        [0.7421, 0.8515, 0.9971]])

In [26]:
torch.index_select(b, dim=0, index=s)

tensor([[[0.4712, 0.3005],
         [0.7368, 0.3270],
         [0.8310, 0.8293]],

        [[0.2569, 0.6295],
         [0.4548, 0.0289],
         [0.9882, 0.3564]],

        [[0.6364, 0.8488],
         [0.4776, 0.9110],
         [0.0848, 0.9282]],

        [[0.7726, 0.2401],
         [0.1018, 0.9630],
         [0.8617, 0.4635]],

        [[0.3909, 0.1082],
         [0.9865, 0.1186],
         [0.9662, 0.9263]]])

## equality

In [27]:
a = torch.tensor([10, 5, 0, 20, 30])
b = torch.tensor([10, 5, 0, 20, 30])

x = torch.eq(a, b)

print(x)
print(x.all())
print(bool(x.all()))

tensor([True, True, True, True, True])
tensor(True)
True


## patching

In [28]:
x = torch.zeros((2, 2, 3, 3))
x

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])

In [29]:
y = torch.ones((2, 2, 3, 3))
y

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [30]:
t = y.clone()
t

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [31]:
t[:, :, 0:2, 0:2] = x[:, :, 0:2, 0:2]
t

tensor([[[[0., 0., 1.],
          [0., 0., 1.],
          [1., 1., 1.]],

         [[0., 0., 1.],
          [0., 0., 1.],
          [1., 1., 1.]]],


        [[[0., 0., 1.],
          [0., 0., 1.],
          [1., 1., 1.]],

         [[0., 0., 1.],
          [0., 0., 1.],
          [1., 1., 1.]]]])

# squeeze, topk & argmax

In [32]:
x = torch.rand(5, 3)
x

tensor([[0.4030, 0.0580, 0.9035],
        [0.3564, 0.3125, 0.4247],
        [0.9381, 0.7482, 0.0972],
        [0.9629, 0.3296, 0.6010],
        [0.1928, 0.0954, 0.9171]])

In [33]:
x[:, 1]

tensor([0.0580, 0.3125, 0.7482, 0.3296, 0.0954])

In [34]:
x.argmax(dim=1)

tensor([2, 2, 0, 0, 2])

In [35]:
x[:, x.argmax(dim=1)]

tensor([[0.9035, 0.9035, 0.4030, 0.4030, 0.9035],
        [0.4247, 0.4247, 0.3564, 0.3564, 0.4247],
        [0.0972, 0.0972, 0.9381, 0.9381, 0.0972],
        [0.6010, 0.6010, 0.9629, 0.9629, 0.6010],
        [0.9171, 0.9171, 0.1928, 0.1928, 0.9171]])

In [36]:
v, _ = x.topk(1, dim=1, sorted=False)
v

tensor([[0.9035],
        [0.4247],
        [0.9381],
        [0.9629],
        [0.9171]])

In [37]:
v.squeeze(dim=1)

tensor([0.9035, 0.4247, 0.9381, 0.9629, 0.9171])