In [1]:
import torch
import numpy as np
from torch.nn import functional as F

## indexing

In [11]:
x = torch.rand(5, 3)
x

tensor([[0.2258, 0.1781, 0.0813],
        [0.3599, 0.9146, 0.0506],
        [0.8452, 0.8539, 0.4890],
        [0.0776, 0.8297, 0.3438],
        [0.9610, 0.1222, 0.9621]])

In [12]:
x.shape

torch.Size([5, 3])

In [13]:
x.shape[1]

3

In [14]:
x[0]

tensor([0.2258, 0.1781, 0.0813])

In [15]:
x[:, [0, 1, 2, 0, 1]]

tensor([[0.2258, 0.1781, 0.0813, 0.2258, 0.1781],
        [0.3599, 0.9146, 0.0506, 0.3599, 0.9146],
        [0.8452, 0.8539, 0.4890, 0.8452, 0.8539],
        [0.0776, 0.8297, 0.3438, 0.0776, 0.8297],
        [0.9610, 0.1222, 0.9621, 0.9610, 0.1222]])

In [6]:
p = torch.zeros(10)
p

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
y = torch.tensor([3, 8, 3, 3, 8, 5])
y

tensor([3, 8, 3, 3, 8, 5])

In [8]:
p.index_add_(0, y, torch.ones(y.shape[0]))
p

tensor([0., 0., 0., 3., 0., 1., 0., 0., 2., 0.])

In [8]:
x = torch.rand(10, 3)
x

tensor([[0.3637, 0.2674, 0.6326],
        [0.1303, 0.7925, 0.8836],
        [0.3115, 0.9276, 0.2520],
        [0.3575, 0.0373, 0.3025],
        [0.3248, 0.8037, 0.1523],
        [0.8999, 0.4756, 0.8958],
        [0.1602, 0.7253, 0.0725],
        [0.8409, 0.2301, 0.8409],
        [0.3789, 0.9843, 0.4330],
        [0.0672, 0.9290, 0.1142]])

In [10]:
v, _ = x.max(dim=1)
v

tensor([0.6326, 0.8836, 0.9276, 0.3575, 0.8037, 0.8999, 0.7253, 0.8409, 0.9843,
        0.9290])

In [11]:
c = torch.from_numpy(np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 1]))
c

tensor([0, 0, 0, 1, 1, 1, 2, 2, 2, 1])

In [15]:
c.unsqueeze(dim=1)

tensor([[0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [1]])

In [18]:
torch.gather(x, dim=1, index=c.unsqueeze(dim=1)).squeeze(dim=1)

tensor([0.3637, 0.1303, 0.3115, 0.0373, 0.8037, 0.4756, 0.0725, 0.8409, 0.4330,
        0.9290])

## dimension manipulation

In [9]:
x = torch.tensor([[0, 1, 1, 1], [2, 2, 0, 0]])
print(x.shape)
x

torch.Size([2, 4])


tensor([[0, 1, 1, 1],
        [2, 2, 0, 0]])

In [10]:
y = F.one_hot(x)
print(y.shape)
y

torch.Size([2, 4, 3])


tensor([[[1, 0, 0],
         [0, 1, 0],
         [0, 1, 0],
         [0, 1, 0]],

        [[0, 0, 1],
         [0, 0, 1],
         [1, 0, 0],
         [1, 0, 0]]])

In [11]:
order = list(range(0, y.ndim))
order.insert(1, order[-1])
del order[-1]
order

[0, 2, 1]

In [12]:
t = y.permute(order)
print(t.shape)
t

torch.Size([2, 3, 4])


tensor([[[1, 0, 0, 0],
         [0, 1, 1, 1],
         [0, 0, 0, 0]],

        [[0, 0, 1, 1],
         [0, 0, 0, 0],
         [1, 1, 0, 0]]])

In [13]:
s = torch.tensor([0.1, 0.2, 0.3, 0.4])
s

tensor([0.1000, 0.2000, 0.3000, 0.4000])

In [14]:
t.float() + s

tensor([[[1.1000, 0.2000, 0.3000, 0.4000],
         [0.1000, 1.2000, 1.3000, 1.4000],
         [0.1000, 0.2000, 0.3000, 0.4000]],

        [[0.1000, 0.2000, 1.3000, 1.4000],
         [0.1000, 0.2000, 0.3000, 0.4000],
         [1.1000, 1.2000, 0.3000, 0.4000]]])

In [15]:
t.float().lerp(s, 0.5)

tensor([[[0.5500, 0.1000, 0.1500, 0.2000],
         [0.0500, 0.6000, 0.6500, 0.7000],
         [0.0500, 0.1000, 0.1500, 0.2000]],

        [[0.0500, 0.1000, 0.6500, 0.7000],
         [0.0500, 0.1000, 0.1500, 0.2000],
         [0.5500, 0.6000, 0.1500, 0.2000]]])

## stack vs cat

In [16]:
x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
y = torch.ones(5, 3)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
c = torch.cat((x, y), dim = 0)
c

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
s = torch.stack((x, y), dim=0)
s

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [20]:
torch.mean(s, dim=0)

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])

## argsort

In [21]:
a = torch.rand((5, 3))
a

tensor([[0.1682, 0.5588, 0.2389],
        [0.2448, 0.4801, 0.7754],
        [0.8878, 0.0942, 0.8037],
        [0.4792, 0.4068, 0.3187],
        [0.7421, 0.8515, 0.9971]])

In [22]:
b = torch.rand((5, 3, 2))
b

tensor([[[0.6364, 0.8488],
         [0.4776, 0.9110],
         [0.0848, 0.9282]],

        [[0.2569, 0.6295],
         [0.4548, 0.0289],
         [0.9882, 0.3564]],

        [[0.4712, 0.3005],
         [0.7368, 0.3270],
         [0.8310, 0.8293]],

        [[0.7726, 0.2401],
         [0.1018, 0.9630],
         [0.8617, 0.4635]],

        [[0.3909, 0.1082],
         [0.9865, 0.1186],
         [0.9662, 0.9263]]])

In [23]:
x = torch.tensor([10, 5, 0, 20, 30])
x

tensor([10,  5,  0, 20, 30])

In [24]:
s = torch.argsort(x)
s

tensor([2, 1, 0, 3, 4])

In [25]:
torch.index_select(a, dim=0, index=s)

tensor([[0.8878, 0.0942, 0.8037],
        [0.2448, 0.4801, 0.7754],
        [0.1682, 0.5588, 0.2389],
        [0.4792, 0.4068, 0.3187],
        [0.7421, 0.8515, 0.9971]])

In [26]:
torch.index_select(b, dim=0, index=s)

tensor([[[0.4712, 0.3005],
         [0.7368, 0.3270],
         [0.8310, 0.8293]],

        [[0.2569, 0.6295],
         [0.4548, 0.0289],
         [0.9882, 0.3564]],

        [[0.6364, 0.8488],
         [0.4776, 0.9110],
         [0.0848, 0.9282]],

        [[0.7726, 0.2401],
         [0.1018, 0.9630],
         [0.8617, 0.4635]],

        [[0.3909, 0.1082],
         [0.9865, 0.1186],
         [0.9662, 0.9263]]])

## equality

In [27]:
a = torch.tensor([10, 5, 0, 20, 30])
b = torch.tensor([10, 5, 0, 20, 30])

x = torch.eq(a, b)

print(x)
print(x.all())
print(bool(x.all()))

tensor([True, True, True, True, True])
tensor(True)
True


## patching

In [28]:
x = torch.zeros((2, 2, 3, 3))
x

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])

In [29]:
y = torch.ones((2, 2, 3, 3))
y

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [30]:
t = y.clone()
t

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [31]:
t[:, :, 0:2, 0:2] = x[:, :, 0:2, 0:2]
t

tensor([[[[0., 0., 1.],
          [0., 0., 1.],
          [1., 1., 1.]],

         [[0., 0., 1.],
          [0., 0., 1.],
          [1., 1., 1.]]],


        [[[0., 0., 1.],
          [0., 0., 1.],
          [1., 1., 1.]],

         [[0., 0., 1.],
          [0., 0., 1.],
          [1., 1., 1.]]]])

# squeeze, topk & argmax

In [32]:
x = torch.rand(5, 3)
x

tensor([[0.4030, 0.0580, 0.9035],
        [0.3564, 0.3125, 0.4247],
        [0.9381, 0.7482, 0.0972],
        [0.9629, 0.3296, 0.6010],
        [0.1928, 0.0954, 0.9171]])

In [33]:
x[:, 1]

tensor([0.0580, 0.3125, 0.7482, 0.3296, 0.0954])

In [34]:
x.argmax(dim=1)

tensor([2, 2, 0, 0, 2])

In [35]:
x[:, x.argmax(dim=1)]

tensor([[0.9035, 0.9035, 0.4030, 0.4030, 0.9035],
        [0.4247, 0.4247, 0.3564, 0.3564, 0.4247],
        [0.0972, 0.0972, 0.9381, 0.9381, 0.0972],
        [0.6010, 0.6010, 0.9629, 0.9629, 0.6010],
        [0.9171, 0.9171, 0.1928, 0.1928, 0.9171]])

In [36]:
v, _ = x.topk(1, dim=1, sorted=False)
v

tensor([[0.9035],
        [0.4247],
        [0.9381],
        [0.9629],
        [0.9171]])

In [37]:
v.squeeze(dim=1)

tensor([0.9035, 0.4247, 0.9381, 0.9629, 0.9171])

# autograd

### simple - ds/dx

In [62]:
x = torch.rand(2, 2, requires_grad=True)
x

tensor([[0.5458, 0.1993],
        [0.7799, 0.1608]], requires_grad=True)

In [63]:
y = x * 2 + 5

y

tensor([[6.0915, 5.3987],
        [6.5598, 5.3216]], grad_fn=<AddBackward0>)

In [64]:
z = y.mean()

In [65]:
print(x.grad_fn)
print(y.grad_fn)
print(z.grad_fn)

None


In [66]:
print(x.grad)
print(y.grad)
print(z.grad)

None
None
None


In [67]:
z.backward()

In [68]:
print(x.grad)
print(y.grad)
print(z.grad)

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])
None
None


### complex - ds/dx

In [78]:
x = torch.ones(2, requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

In [80]:
y = torch.zeros(3)
y[0] = 5 * x[0] * x[1]
y[1] = 2 * x[0] + 3 * x[1]
y[2] = 7 * x[0] + 10
y

tensor([ 5.,  5., 17.], grad_fn=<CopySlices>)

In [82]:
z = y.mean()
z

tensor(9., grad_fn=<MeanBackward0>)

In [83]:
print(x.grad_fn)
print(y.grad_fn)
print(z.grad_fn)

None


In [84]:
print(x.grad)
print(y.grad)
print(z.grad)

None
None
None


In [85]:
z.backward()

In [86]:
print(x.grad)
print(y.grad)
print(z.grad)

tensor([4.6667, 2.6667])
None
None


### simple - dy/dx

In [95]:
x = torch.rand(2, 2, requires_grad=True)
x

tensor([[0.2649, 0.5406],
        [0.9137, 0.3129]], requires_grad=True)

In [96]:
y = x ** 2
y

tensor([[0.0702, 0.2923],
        [0.8348, 0.0979]], grad_fn=<PowBackward0>)

In [97]:
print(x.grad_fn)
print(y.grad_fn)

None


In [98]:
l = torch.ones(y.shape)
y.backward(l)

In [99]:
print(x.grad)
print(y.grad)

tensor([[0.5297, 1.0812],
        [1.8273, 0.6257]])
None


### complex - dy/dx

In [100]:
x = torch.rand(2, 2, requires_grad=True)
x

tensor([[0.5238, 0.9734],
        [0.1168, 0.2547]], requires_grad=True)

In [101]:
y = torch.zeros(2, 2)
y[0][0] = 5 * x[0][0] * x[0][1]
y[0][1] = 2 * x[0][0] + 3 * x[0][1]
y[1][0] = x[1][1] * x[1][0] **2
y[1][1] = 4 * x[1][0] - 2 * x[1][1]
y

tensor([[ 2.5493e+00,  3.9678e+00],
        [ 3.4758e-03, -4.2027e-02]], grad_fn=<CopySlices>)

In [102]:
print(x.grad_fn)
print(y.grad_fn)

None


In [103]:
l = torch.ones(y.shape)
y.backward(l)

In [104]:
print(x.grad)
print(y.grad)

tensor([[ 6.8670,  5.6189],
        [ 4.0595, -1.9864]])
None


In [110]:
print([
    [float(5 * x[0][1] + 2), float(5 * x[0][0] + 3)], 
    [float(2 * x[1][0] * x[1][1] + 4), float(x[1][0] ** 2 - 2)]
])

[[6.867044448852539, 5.61894416809082], [4.059503078460693, -1.9863516092300415]]


## broadcasting

In [4]:
x = torch.rand(4, 3, 2)
x

tensor([[[0.3228, 0.7756],
         [0.6063, 0.0913],
         [0.1535, 0.0618]],

        [[0.9075, 0.7559],
         [0.1636, 0.1031],
         [0.3610, 0.4356]],

        [[0.5874, 0.9444],
         [0.5633, 0.4424],
         [0.3312, 0.5933]],

        [[0.1605, 0.0525],
         [0.3212, 0.0232],
         [0.8984, 0.4965]]])

In [11]:
x[0]

tensor([[0.3228, 0.7756],
        [0.6063, 0.0913],
        [0.1535, 0.0618]])

In [19]:
x[0].max()

tensor(0.7756)

In [14]:
x.view(x.shape[0], -1)

tensor([[0.3228, 0.7756, 0.6063, 0.0913, 0.1535, 0.0618],
        [0.9075, 0.7559, 0.1636, 0.1031, 0.3610, 0.4356],
        [0.5874, 0.9444, 0.5633, 0.4424, 0.3312, 0.5933],
        [0.1605, 0.0525, 0.3212, 0.0232, 0.8984, 0.4965]])

In [18]:
v, _ = x.view(x.shape[0], -1).max(dim=1)
v

tensor([0.7756, 0.9075, 0.9444, 0.8984])

In [22]:
x / v.view(v.shape[0], 1, 1)

tensor([[[0.4162, 1.0000],
         [0.7817, 0.1177],
         [0.1980, 0.0797]],

        [[1.0000, 0.8330],
         [0.1803, 0.1136],
         [0.3978, 0.4800]],

        [[0.6220, 1.0000],
         [0.5965, 0.4685],
         [0.3507, 0.6283]],

        [[0.1787, 0.0584],
         [0.3575, 0.0258],
         [1.0000, 0.5527]]])

In [25]:
y = torch.from_numpy(np.array([1, 0, 2, -1]))
y

tensor([ 1,  0,  2, -1])

In [27]:
x * y.view(y.shape[0], 1, 1)

tensor([[[ 0.3228,  0.7756],
         [ 0.6063,  0.0913],
         [ 0.1535,  0.0618]],

        [[ 0.0000,  0.0000],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]],

        [[ 1.1748,  1.8887],
         [ 1.1265,  0.8848],
         [ 0.6624,  1.1866]],

        [[-0.1605, -0.0525],
         [-0.3212, -0.0232],
         [-0.8984, -0.4965]]])